/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vue;

import Controleur.CtrlAbstrait;
import Controleur.CtrlMenu;
import javax.swing.JCheckBox;

/**
 *
 * @author btssio
 */
public class VueMenu extends VueAbstrait {
    
    protected CtrlMenu ctrlM;
    /**
     * Creates new form Vue_Menu
     */
    public VueMenu(CtrlAbstrait ctrlA) {
        super(ctrlA);
        initComponents();
        VueAbstrait vueA = null;
        this.ctrlM = new CtrlMenu(this, vueA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxComptesRendus = new javax.swing.JCheckBox();
        jCheckBoxVisiteurs = new javax.swing.JCheckBox();
        jCheckBoxPracticiens = new javax.swing.JCheckBox();
        jCheckBoxMedicaments = new javax.swing.JCheckBox();
        jCheckBoxQuit = new javax.swing.JCheckBox();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jLabelTitre = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckBoxComptesRendus.setText("Comptes-Rendus");
        jCheckBoxComptesRendus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxComptesRendusActionPerformed(evt);
            }
        });

        jCheckBoxVisiteurs.setText("Visiteurs");
        jCheckBoxVisiteurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxVisiteursActionPerformed(evt);
            }
        });

        jCheckBoxPracticiens.setText("Practiciens");
        jCheckBoxPracticiens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPracticiensActionPerformed(evt);
            }
        });

        jCheckBoxMedicaments.setText("Medicaments");
        jCheckBoxMedicaments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMedicamentsActionPerformed(evt);
            }
        });

        jCheckBoxQuit.setText("Quitter");
        jCheckBoxQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxQuitActionPerformed(evt);
            }
        });

        jLabelTitre.setText("Gestion des comptes rendus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxComptesRendus)
                            .addComponent(jCheckBoxMedicaments)
                            .addComponent(jCheckBoxQuit)
                            .addComponent(jCheckBoxPracticiens)
                            .addComponent(jCheckBoxVisiteurs)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabelTitre)))
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabelTitre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jCheckBoxComptesRendus)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxVisiteurs)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxPracticiens)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxMedicaments)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxQuit)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jCheckBoxComptesRendusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxComptesRendusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxComptesRendusActionPerformed
    private void jCheckBoxVisiteursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxVisiteursActionPerformed
        this.getCtrlM().afficherVisiteur();
    }//GEN-LAST:event_jCheckBoxVisiteursActionPerformed
    private void jCheckBoxPracticiensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPracticiensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPracticiensActionPerformed
    private void jCheckBoxMedicamentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMedicamentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMedicamentsActionPerformed
    private void jCheckBoxQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxQuitActionPerformed
        this.getCtrlM().close();
    }//GEN-LAST:event_jCheckBoxQuitActionPerformed

    public CtrlMenu getCtrlM() {
        return ctrlM;
    }

    public void setCtrlM(CtrlMenu ctrlM) {
        this.ctrlM = ctrlM;
    }

    public JCheckBox getjCheckBoxComptesRendus() {
        return jCheckBoxComptesRendus;
    }

    public void setjCheckBoxComptesRendus(JCheckBox jCheckBoxComptesRendus) {
        this.jCheckBoxComptesRendus = jCheckBoxComptesRendus;
    }

    public JCheckBox getjCheckBoxMedicaments() {
        return jCheckBoxMedicaments;
    }

    public void setjCheckBoxMedicaments(JCheckBox jCheckBoxMedicaments) {
        this.jCheckBoxMedicaments = jCheckBoxMedicaments;
    }

    public JCheckBox getjCheckBoxPracticiens() {
        return jCheckBoxPracticiens;
    }

    public void setjCheckBoxPracticiens(JCheckBox jCheckBoxPracticiens) {
        this.jCheckBoxPracticiens = jCheckBoxPracticiens;
    }

    public JCheckBox getjCheckBoxQuit() {
        return jCheckBoxQuit;
    }

    public void setjCheckBoxQuit(JCheckBox jCheckBoxQuit) {
        this.jCheckBoxQuit = jCheckBoxQuit;
    }

    public JCheckBox getjCheckBoxVisiteurs() {
        return jCheckBoxVisiteurs;
    }

    public void setjCheckBoxVisiteurs(JCheckBox jCheckBoxVisiteurs) {
        this.jCheckBoxVisiteurs = jCheckBoxVisiteurs;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JCheckBox jCheckBoxComptesRendus;
    private javax.swing.JCheckBox jCheckBoxMedicaments;
    private javax.swing.JCheckBox jCheckBoxPracticiens;
    private javax.swing.JCheckBox jCheckBoxQuit;
    private javax.swing.JCheckBox jCheckBoxVisiteurs;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
